<?xml version="1.0" encoding="utf-8"?><Database Name="DB" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DB.mdf;Integrated Security=True" SettingsObjectName="FoodOrderingSystem.My.MySettings" SettingsPropertyName="DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="Id" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(90)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[Group]" Member="Group" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="[Food Image]" Member="Food_Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="StaffID" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StaffFirstName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StaffMiddleName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StaffLastName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CIty" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PlaceOfBirth" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ICNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumEmergency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JobPosition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateHired" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DailyRate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JobType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayMethod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JobStatus" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="StaffImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Redeem" Member="Redeems">
    <Type Name="Redeem">
      <Column Name="ProductId" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Availability" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Picture" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.payedFood" Member="payedFoods">
    <Type Name="payedFood">
      <Column Name="payedFood_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="payment_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="food_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="food_quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="food_totalPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="pay_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="pay_time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="payment_ID" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="payment_method" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="payment_totalPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="member_id" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="Id" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ProfileImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Points" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>